// <auto-generated />
namespace Project2WooxTravel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class m71 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m71));
        
        string IMigrationMetadata.Id
        {
            get { return "202410221745082_m71"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
